### ISSUE TITLE
A little more explanation request, please

### ISSUE THREAD

**Issue by Jeff17Robbins** [webcomponents/html-imports#70]
> The polyfill appends the imported contents to the <link> itself to leverage the native implementation of Custom Elements, which expects scripts upgrading the CustomElementRegistry to be connected to the main document.

I don't understand this sentence.  To start with, I don't understand the expectation of native Custom Elements.  What does "upgrading the CustomElementRegistry" mean?   When does an imported script under native HTML Imports get connected to the main document?  What native feature is the polyfill emulating, since I thought a native import is hidden inside an `.import` documentFragment?  

And what is the "leverage" this sentence speaks of?  Is there a use case of running this HTML Imports with native Custom Elements?  

Sorry, but I'm obviously very confused about the intent of **not** emulating the `.import` property!

**Comment by valdrinkoshi** [comment]
The `CustomElementRegistry` gets upgraded when we define a new Custom Element:
```js
customElements.define('my-element', MyElement extends HTMLElement { ... })
```

Under native CustomElements, if the script is run in a disconnected document and not the main one, the registry won't be updated, e.g.
```js
const theScript = document.createElement('script');
theScript.innerHTML = `customElements.define('my-element', MyElement extends HTMLElement { ... })`;
const newDoc = document.implementation.createHTMLDocument('new-doc');
newDoc.head.appendChild(theScript);
```
Native HTMLImports will make sure each import is connected & can access to the main document, and this is not polyfillable.

We achieve a similar behavior by appending the scripts into the main document instead of creating a separate, disconnected one.

Would adding a description like this be clearer?

**Comment by Jeff17Robbins** [comment]
I'm getting there.   :-)

I think maybe you are still leaving some steps out, no doubt because they are obvious to you and probably not worth stating?

The code snippet you show is presumably motivated by how, for example, HTML Imports V0 polyfill works, by dropping the imported text into newDoc.  But then that code won't work.  

So, to make that code work, you need the container to be in the main document?

What is the use-case of that code snippet?  Is it common?  If it were a corner case, for example, I'd sacrifice it in exchange for not polluting the document with all the imports. (Because fancier selectors needed etc to exclude the pollution...)

**Comment by valdrinkoshi** [comment]
Oh yeah I was trying to leave out implementation details where possible, hoping it would help :)
The previous code snippet aims to show the approach taken by the HTMLImports v0 implementation, which would load the contents of the html files and create a disconnected document where to host the html (create elements, execute scripts, etc).
Here the revisited example, try it on chrome or safari:
```html
  <my-element></my-element>

  <script>
    const theScript = document.createElement('script');
    theScript.innerHTML = `customElements.define('my-element', class MyElement extends HTMLElement { 
constructor() {
  super();
  console.log('my-element!');
} })`;
    const newDoc = document.implementation.createHTMLDocument('new-doc');
    newDoc.head.appendChild(theScript);
    // Reparenting the script won't work, as it was already executed in newDoc!
    document.head.appendChild(theScript);
  </script>
```
^ by commenting `newDoc.head.appendChild(theScript)`, you'll see that `my-element` gets upgraded.

In native Custom Elements v1, executing scripts that define a new custom element into a disconnected document won't update the [`CustomElementsRegistry`](https://www.w3.org/TR/custom-elements/#custom-elements-api) (as each document has its own), hence we execute the scripts into the main document.

On top of that, consider that creating a disconnected document is more expensive compared to appending content in the main document.
Also, you need to have stylesheets in the main document in order to apply; HTMLImports v0 has to move the stylesheets into the main document, whereas in v1 we directly put them in the right place.

**Comment by Jeff17Robbins** [comment]
Thanks, makes sense.  It made me curious as to what "magic" is used by the native `link.import` to be both a separate document and also defer `customElements.defineElement()` to the main document.  How does that work?!

**Comment by valdrinkoshi** [comment]
Yeah, HTMLImports magic includes giving imports access to the main document, in a similar fashion as `window.top` gives an iframe access to the window which contains it. [The spec](https://www.w3.org/TR/html-imports/) provides more details on the inner guts of this 📖

**Comment by Jeff17Robbins** [comment]
I just spent some time (probably not enough!) trying to find the magic in
that spec -- any hints as to which section or which concept imbues the
import with this super power?

**Comment by valdrinkoshi** [comment]
I think this is a consequence of [Step 9.2](https://www.w3.org/TR/html-imports/#additions-to-dom-document-currentscript) which describes how `document.currentScript` should be modified, in particular:
> When the Document is created, the currentScript must be initialized to null. If the Document is an imported document, its currentScript is always null.

From the Custom Elements spec, check [points 13, 14 of Element definition](https://www.w3.org/TR/custom-elements/#element-definition), which imply the definition should update the elements of the common document.

PS: consider that HTMLImports is currently implemented only on Chrome while other browsers are on hold for its implementation, and that the more likely evolution of this API might be HTML Modules, you can follow the discussion about that here https://github.com/w3c/webcomponents/issues/645.

**Comment by Jeff17Robbins** [comment]
Thanks for those pointers. I appreciate it. The discussion link is really
interesting.  Long, but looks worth reading!

**Comment by valdrinkoshi** [comment]
@Jeff17Robbins do you think the README can be further improved or can we close this issue?

**Comment by Jeff17Robbins** [comment]
Yes, go ahead and close the issue.
