### ISSUE TITLE
Reverse, inconsistent order of `onload` callbacks

### ISSUE THREAD

**Issue by tomalec** [webcomponents/html-imports#79]
### Description
In  v1 polyfil, in oppose to native and v0 `onload` callbacks are called in reverse order

#### Live Demo
http://jsbin.com/filelih/3/edit?html,console,output

#### Steps to Reproduce
1. Create `link rel="import` for the_url_, attach _first_ `onload` callback
1. Create `link rel="import` for the _url_, attach _second_ `onload` callback
1. Create `link rel="import` for the _url_, attach _third_ `onload` callback
2. Wait for the imported document to be loaded
3. Check callback execution order

#### Expected Results
Callbacks should be called in assignment order: _first, second, third_.
(As in Chrome and V0 polyfill)

#### Actual Results
Callbacks are called in reversed order of assignment: _third, second, first_.

### Browsers Affected
- [ ] Chrome
- [x] Firefox
- [x] Edge
- [?] Safari 9
- [?] Safari 8
- [x] IE 11

### Versions

- webcomponents: @532d5dd  (master)

**Comment by valdrinkoshi** [comment]
This is done [here](https://github.com/webcomponents/html-imports/blob/master/src/html-imports.js#L485) in order to fire the deepest imports before firing the outer-most ones, as imports contained in another import should be firing load/error events, then the parent import can fire its load/error event. The reason we do the inverse order is for performance and implementation simplicity (only a `querySelectorAll` and traverse it in the inverse order).

What is the scenario where this causes an issue? Scripts loading order is already ensured by the polyfill, and by the time we fire the events, all scripts have been already executed.

**Comment by azakus** [comment]
HTML Imports are deprecated, and we are only making critical bug fixes.
